# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lyorig/Documents/Programming/Quest/halcyon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lyorig/Documents/Programming/Quest/halcyon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lyorig/Documents/Programming/Quest/halcyon/CMakeFiles /Users/lyorig/Documents/Programming/Quest/halcyon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lyorig/Documents/Programming/Quest/halcyon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named HalTest

# Build rule for target.
HalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HalTest
.PHONY : HalTest

# fast build rule for target.
HalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/build
.PHONY : HalTest/fast

src/context.o: src/context.cpp.o
.PHONY : src/context.o

# target to build an object file
src/context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/context.cpp.o
.PHONY : src/context.cpp.o

src/context.i: src/context.cpp.i
.PHONY : src/context.i

# target to preprocess a source file
src/context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/context.cpp.i
.PHONY : src/context.cpp.i

src/context.s: src/context.cpp.s
.PHONY : src/context.s

# target to generate assembly for a file
src/context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/context.cpp.s
.PHONY : src/context.cpp.s

src/debug.o: src/debug.cpp.o
.PHONY : src/debug.o

# target to build an object file
src/debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/debug.cpp.o
.PHONY : src/debug.cpp.o

src/debug.i: src/debug.cpp.i
.PHONY : src/debug.i

# target to preprocess a source file
src/debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/debug.cpp.i
.PHONY : src/debug.cpp.i

src/debug.s: src/debug.cpp.s
.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/debug.cpp.s
.PHONY : src/debug.cpp.s

src/event.o: src/event.cpp.o
.PHONY : src/event.o

# target to build an object file
src/event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event.cpp.o
.PHONY : src/event.cpp.o

src/event.i: src/event.cpp.i
.PHONY : src/event.i

# target to preprocess a source file
src/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event.cpp.i
.PHONY : src/event.cpp.i

src/event.s: src/event.cpp.s
.PHONY : src/event.s

# target to generate assembly for a file
src/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event.cpp.s
.PHONY : src/event.cpp.s

src/event/handler.o: src/event/handler.cpp.o
.PHONY : src/event/handler.o

# target to build an object file
src/event/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/handler.cpp.o
.PHONY : src/event/handler.cpp.o

src/event/handler.i: src/event/handler.cpp.i
.PHONY : src/event/handler.i

# target to preprocess a source file
src/event/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/handler.cpp.i
.PHONY : src/event/handler.cpp.i

src/event/handler.s: src/event/handler.cpp.s
.PHONY : src/event/handler.s

# target to generate assembly for a file
src/event/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/handler.cpp.s
.PHONY : src/event/handler.cpp.s

src/event/keyboard.o: src/event/keyboard.cpp.o
.PHONY : src/event/keyboard.o

# target to build an object file
src/event/keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/keyboard.cpp.o
.PHONY : src/event/keyboard.cpp.o

src/event/keyboard.i: src/event/keyboard.cpp.i
.PHONY : src/event/keyboard.i

# target to preprocess a source file
src/event/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/keyboard.cpp.i
.PHONY : src/event/keyboard.cpp.i

src/event/keyboard.s: src/event/keyboard.cpp.s
.PHONY : src/event/keyboard.s

# target to generate assembly for a file
src/event/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/keyboard.cpp.s
.PHONY : src/event/keyboard.cpp.s

src/event/mouse.o: src/event/mouse.cpp.o
.PHONY : src/event/mouse.o

# target to build an object file
src/event/mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/mouse.cpp.o
.PHONY : src/event/mouse.cpp.o

src/event/mouse.i: src/event/mouse.cpp.i
.PHONY : src/event/mouse.i

# target to preprocess a source file
src/event/mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/mouse.cpp.i
.PHONY : src/event/mouse.cpp.i

src/event/mouse.s: src/event/mouse.cpp.s
.PHONY : src/event/mouse.s

# target to generate assembly for a file
src/event/mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/mouse.cpp.s
.PHONY : src/event/mouse.cpp.s

src/event/types.o: src/event/types.cpp.o
.PHONY : src/event/types.o

# target to build an object file
src/event/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/types.cpp.o
.PHONY : src/event/types.cpp.o

src/event/types.i: src/event/types.cpp.i
.PHONY : src/event/types.i

# target to preprocess a source file
src/event/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/types.cpp.i
.PHONY : src/event/types.cpp.i

src/event/types.s: src/event/types.cpp.s
.PHONY : src/event/types.s

# target to generate assembly for a file
src/event/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/event/types.cpp.s
.PHONY : src/event/types.cpp.s

src/image.o: src/image.cpp.o
.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/internal/accessor.o: src/internal/accessor.cpp.o
.PHONY : src/internal/accessor.o

# target to build an object file
src/internal/accessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/internal/accessor.cpp.o
.PHONY : src/internal/accessor.cpp.o

src/internal/accessor.i: src/internal/accessor.cpp.i
.PHONY : src/internal/accessor.i

# target to preprocess a source file
src/internal/accessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/internal/accessor.cpp.i
.PHONY : src/internal/accessor.cpp.i

src/internal/accessor.s: src/internal/accessor.cpp.s
.PHONY : src/internal/accessor.s

# target to generate assembly for a file
src/internal/accessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/internal/accessor.cpp.s
.PHONY : src/internal/accessor.cpp.s

src/surface.o: src/surface.cpp.o
.PHONY : src/surface.o

# target to build an object file
src/surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/surface.cpp.o
.PHONY : src/surface.cpp.o

src/surface.i: src/surface.cpp.i
.PHONY : src/surface.i

# target to preprocess a source file
src/surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/surface.cpp.i
.PHONY : src/surface.cpp.i

src/surface.s: src/surface.cpp.s
.PHONY : src/surface.s

# target to generate assembly for a file
src/surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/surface.cpp.s
.PHONY : src/surface.cpp.s

src/ttf.o: src/ttf.cpp.o
.PHONY : src/ttf.o

# target to build an object file
src/ttf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/ttf.cpp.o
.PHONY : src/ttf.cpp.o

src/ttf.i: src/ttf.cpp.i
.PHONY : src/ttf.i

# target to preprocess a source file
src/ttf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/ttf.cpp.i
.PHONY : src/ttf.cpp.i

src/ttf.s: src/ttf.cpp.s
.PHONY : src/ttf.s

# target to generate assembly for a file
src/ttf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/ttf.cpp.s
.PHONY : src/ttf.cpp.s

src/types/templates.o: src/types/templates.cpp.o
.PHONY : src/types/templates.o

# target to build an object file
src/types/templates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/types/templates.cpp.o
.PHONY : src/types/templates.cpp.o

src/types/templates.i: src/types/templates.cpp.i
.PHONY : src/types/templates.i

# target to preprocess a source file
src/types/templates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/types/templates.cpp.i
.PHONY : src/types/templates.cpp.i

src/types/templates.s: src/types/templates.cpp.s
.PHONY : src/types/templates.s

# target to generate assembly for a file
src/types/templates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/types/templates.cpp.s
.PHONY : src/types/templates.cpp.s

src/utility/printing.o: src/utility/printing.cpp.o
.PHONY : src/utility/printing.o

# target to build an object file
src/utility/printing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/printing.cpp.o
.PHONY : src/utility/printing.cpp.o

src/utility/printing.i: src/utility/printing.cpp.i
.PHONY : src/utility/printing.i

# target to preprocess a source file
src/utility/printing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/printing.cpp.i
.PHONY : src/utility/printing.cpp.i

src/utility/printing.s: src/utility/printing.cpp.s
.PHONY : src/utility/printing.s

# target to generate assembly for a file
src/utility/printing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/printing.cpp.s
.PHONY : src/utility/printing.cpp.s

src/utility/strutil.o: src/utility/strutil.cpp.o
.PHONY : src/utility/strutil.o

# target to build an object file
src/utility/strutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/strutil.cpp.o
.PHONY : src/utility/strutil.cpp.o

src/utility/strutil.i: src/utility/strutil.cpp.i
.PHONY : src/utility/strutil.i

# target to preprocess a source file
src/utility/strutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/strutil.cpp.i
.PHONY : src/utility/strutil.cpp.i

src/utility/strutil.s: src/utility/strutil.cpp.s
.PHONY : src/utility/strutil.s

# target to generate assembly for a file
src/utility/strutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/strutil.cpp.s
.PHONY : src/utility/strutil.cpp.s

src/utility/timer.o: src/utility/timer.cpp.o
.PHONY : src/utility/timer.o

# target to build an object file
src/utility/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/timer.cpp.o
.PHONY : src/utility/timer.cpp.o

src/utility/timer.i: src/utility/timer.cpp.i
.PHONY : src/utility/timer.i

# target to preprocess a source file
src/utility/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/timer.cpp.i
.PHONY : src/utility/timer.cpp.i

src/utility/timer.s: src/utility/timer.cpp.s
.PHONY : src/utility/timer.s

# target to generate assembly for a file
src/utility/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/utility/timer.cpp.s
.PHONY : src/utility/timer.cpp.s

src/video.o: src/video.cpp.o
.PHONY : src/video.o

# target to build an object file
src/video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video.cpp.o
.PHONY : src/video.cpp.o

src/video.i: src/video.cpp.i
.PHONY : src/video.i

# target to preprocess a source file
src/video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video.cpp.i
.PHONY : src/video.cpp.i

src/video.s: src/video.cpp.s
.PHONY : src/video.s

# target to generate assembly for a file
src/video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video.cpp.s
.PHONY : src/video.cpp.s

src/video/display.o: src/video/display.cpp.o
.PHONY : src/video/display.o

# target to build an object file
src/video/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/display.cpp.o
.PHONY : src/video/display.cpp.o

src/video/display.i: src/video/display.cpp.i
.PHONY : src/video/display.i

# target to preprocess a source file
src/video/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/display.cpp.i
.PHONY : src/video/display.cpp.i

src/video/display.s: src/video/display.cpp.s
.PHONY : src/video/display.s

# target to generate assembly for a file
src/video/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/display.cpp.s
.PHONY : src/video/display.cpp.s

src/video/driver.o: src/video/driver.cpp.o
.PHONY : src/video/driver.o

# target to build an object file
src/video/driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/driver.cpp.o
.PHONY : src/video/driver.cpp.o

src/video/driver.i: src/video/driver.cpp.i
.PHONY : src/video/driver.i

# target to preprocess a source file
src/video/driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/driver.cpp.i
.PHONY : src/video/driver.cpp.i

src/video/driver.s: src/video/driver.cpp.s
.PHONY : src/video/driver.s

# target to generate assembly for a file
src/video/driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/driver.cpp.s
.PHONY : src/video/driver.cpp.s

src/video/renderer.o: src/video/renderer.cpp.o
.PHONY : src/video/renderer.o

# target to build an object file
src/video/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/renderer.cpp.o
.PHONY : src/video/renderer.cpp.o

src/video/renderer.i: src/video/renderer.cpp.i
.PHONY : src/video/renderer.i

# target to preprocess a source file
src/video/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/renderer.cpp.i
.PHONY : src/video/renderer.cpp.i

src/video/renderer.s: src/video/renderer.cpp.s
.PHONY : src/video/renderer.s

# target to generate assembly for a file
src/video/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/renderer.cpp.s
.PHONY : src/video/renderer.cpp.s

src/video/texture.o: src/video/texture.cpp.o
.PHONY : src/video/texture.o

# target to build an object file
src/video/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/texture.cpp.o
.PHONY : src/video/texture.cpp.o

src/video/texture.i: src/video/texture.cpp.i
.PHONY : src/video/texture.i

# target to preprocess a source file
src/video/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/texture.cpp.i
.PHONY : src/video/texture.cpp.i

src/video/texture.s: src/video/texture.cpp.s
.PHONY : src/video/texture.s

# target to generate assembly for a file
src/video/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/texture.cpp.s
.PHONY : src/video/texture.cpp.s

src/video/window.o: src/video/window.cpp.o
.PHONY : src/video/window.o

# target to build an object file
src/video/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/window.cpp.o
.PHONY : src/video/window.cpp.o

src/video/window.i: src/video/window.cpp.i
.PHONY : src/video/window.i

# target to preprocess a source file
src/video/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/window.cpp.i
.PHONY : src/video/window.cpp.i

src/video/window.s: src/video/window.cpp.s
.PHONY : src/video/window.s

# target to generate assembly for a file
src/video/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/src/video/window.cpp.s
.PHONY : src/video/window.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HalTest.dir/build.make CMakeFiles/HalTest.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... HalTest"
	@echo "... src/context.o"
	@echo "... src/context.i"
	@echo "... src/context.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/event.o"
	@echo "... src/event.i"
	@echo "... src/event.s"
	@echo "... src/event/handler.o"
	@echo "... src/event/handler.i"
	@echo "... src/event/handler.s"
	@echo "... src/event/keyboard.o"
	@echo "... src/event/keyboard.i"
	@echo "... src/event/keyboard.s"
	@echo "... src/event/mouse.o"
	@echo "... src/event/mouse.i"
	@echo "... src/event/mouse.s"
	@echo "... src/event/types.o"
	@echo "... src/event/types.i"
	@echo "... src/event/types.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/internal/accessor.o"
	@echo "... src/internal/accessor.i"
	@echo "... src/internal/accessor.s"
	@echo "... src/surface.o"
	@echo "... src/surface.i"
	@echo "... src/surface.s"
	@echo "... src/ttf.o"
	@echo "... src/ttf.i"
	@echo "... src/ttf.s"
	@echo "... src/types/templates.o"
	@echo "... src/types/templates.i"
	@echo "... src/types/templates.s"
	@echo "... src/utility/printing.o"
	@echo "... src/utility/printing.i"
	@echo "... src/utility/printing.s"
	@echo "... src/utility/strutil.o"
	@echo "... src/utility/strutil.i"
	@echo "... src/utility/strutil.s"
	@echo "... src/utility/timer.o"
	@echo "... src/utility/timer.i"
	@echo "... src/utility/timer.s"
	@echo "... src/video.o"
	@echo "... src/video.i"
	@echo "... src/video.s"
	@echo "... src/video/display.o"
	@echo "... src/video/display.i"
	@echo "... src/video/display.s"
	@echo "... src/video/driver.o"
	@echo "... src/video/driver.i"
	@echo "... src/video/driver.s"
	@echo "... src/video/renderer.o"
	@echo "... src/video/renderer.i"
	@echo "... src/video/renderer.s"
	@echo "... src/video/texture.o"
	@echo "... src/video/texture.i"
	@echo "... src/video/texture.s"
	@echo "... src/video/window.o"
	@echo "... src/video/window.i"
	@echo "... src/video/window.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

